// <auto-generated />
namespace Battleships
{
    public partial class BattleshipsForm
    {
        /// <summary>
        /// Required form designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up resources used.
        /// </summary>
        /// <param name="disposing">True if managed resources should be deleted; otherwise false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Vom Windows Form-Designer generierter Code

        /// <summary>
        /// Required method for the form designer support.
        /// The contents of the method must not be changed with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(BattleshipsForm));
            this.btnCruiser = new System.Windows.Forms.Button();
            this.btnBattleship = new System.Windows.Forms.Button();
            this.btnBoat = new System.Windows.Forms.Button();
            this.lblGalley = new System.Windows.Forms.Label();
            this.btnGalley = new System.Windows.Forms.Button();
            this.lblBattleship = new System.Windows.Forms.Label();
            this.lblCruiser = new System.Windows.Forms.Label();
            this.lblBoat = new System.Windows.Forms.Label();
            this.toolTipMouse = new System.Windows.Forms.ToolTip(this.components);
            this.menuStripMain = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.networkToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.hostToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.joinToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.playerLabel = new System.Windows.Forms.Label();
            this.enemyLabel = new System.Windows.Forms.Label();
            this.menuStripMain.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnCruiser
            // 
            this.btnCruiser.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCruiser.BackColor = System.Drawing.Color.Transparent;
            this.btnCruiser.BackgroundImage = global::Battleships.Properties.Resources.btn_cruiser;
            this.btnCruiser.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnCruiser.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(166)))), ((int)(((byte)(114)))));
            this.btnCruiser.FlatAppearance.BorderSize = 0;
            this.btnCruiser.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.btnCruiser.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.btnCruiser.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCruiser.ForeColor = System.Drawing.SystemColors.MenuText;
            this.btnCruiser.Location = new System.Drawing.Point(348, 324);
            this.btnCruiser.Margin = new System.Windows.Forms.Padding(4);
            this.btnCruiser.Name = "btnCruiser";
            this.btnCruiser.Size = new System.Drawing.Size(106, 40);
            this.btnCruiser.TabIndex = 5;
            this.btnCruiser.UseVisualStyleBackColor = false;
            this.btnCruiser.MouseDown += new System.Windows.Forms.MouseEventHandler(this.ButtonCruiserMouseDown);
            this.btnCruiser.MouseEnter += new System.EventHandler(this.ButtonCruiserMouseEnter);
            this.btnCruiser.MouseLeave += new System.EventHandler(this.ButtonCruiserMouseLeave);
            // 
            // btnBattleship
            // 
            this.btnBattleship.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBattleship.BackColor = System.Drawing.Color.Transparent;
            this.btnBattleship.BackgroundImage = global::Battleships.Properties.Resources.btn_z;
            this.btnBattleship.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnBattleship.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(166)))), ((int)(((byte)(114)))));
            this.btnBattleship.FlatAppearance.BorderSize = 0;
            this.btnBattleship.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.btnBattleship.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.btnBattleship.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBattleship.ForeColor = System.Drawing.SystemColors.MenuText;
            this.btnBattleship.Location = new System.Drawing.Point(348, 196);
            this.btnBattleship.Margin = new System.Windows.Forms.Padding(4);
            this.btnBattleship.Name = "btnBattleship";
            this.btnBattleship.Size = new System.Drawing.Size(106, 40);
            this.btnBattleship.TabIndex = 6;
            this.btnBattleship.UseVisualStyleBackColor = false;
            this.btnBattleship.MouseDown += new System.Windows.Forms.MouseEventHandler(this.ButtonBattleshipMouseDown);
            this.btnBattleship.MouseEnter += new System.EventHandler(this.ButtonBattleshipMouseEnter);
            this.btnBattleship.MouseLeave += new System.EventHandler(this.ButtonBattleshipMouseLeave);
            // 
            // btnBoat
            // 
            this.btnBoat.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBoat.BackColor = System.Drawing.Color.Transparent;
            this.btnBoat.BackgroundImage = global::Battleships.Properties.Resources.btn_boat;
            this.btnBoat.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnBoat.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(166)))), ((int)(((byte)(114)))));
            this.btnBoat.FlatAppearance.BorderSize = 0;
            this.btnBoat.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.btnBoat.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.btnBoat.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBoat.ForeColor = System.Drawing.SystemColors.MenuText;
            this.btnBoat.Location = new System.Drawing.Point(348, 388);
            this.btnBoat.Margin = new System.Windows.Forms.Padding(4);
            this.btnBoat.Name = "btnBoat";
            this.btnBoat.Size = new System.Drawing.Size(106, 40);
            this.btnBoat.TabIndex = 7;
            this.btnBoat.UseVisualStyleBackColor = false;
            this.btnBoat.MouseDown += new System.Windows.Forms.MouseEventHandler(this.ButtonBoatMouseDown);
            this.btnBoat.MouseEnter += new System.EventHandler(this.ButtonBoatMouseEnter);
            this.btnBoat.MouseLeave += new System.EventHandler(this.ButtonBoatMouseLeave);
            // 
            // lblGalley
            // 
            this.lblGalley.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.lblGalley.AutoSize = true;
            this.lblGalley.BackColor = System.Drawing.Color.Transparent;
            this.lblGalley.Font = new System.Drawing.Font("Segoe Print", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblGalley.ForeColor = System.Drawing.Color.AliceBlue;
            this.lblGalley.Location = new System.Drawing.Point(348, 236);
            this.lblGalley.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblGalley.Name = "lblGalley";
            this.lblGalley.Size = new System.Drawing.Size(106, 30);
            this.lblGalley.TabIndex = 8;
            this.lblGalley.Text = "Number: 1";
            this.lblGalley.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // btnGalley
            // 
            this.btnGalley.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.btnGalley.BackColor = System.Drawing.Color.Transparent;
            this.btnGalley.BackgroundImage = global::Battleships.Properties.Resources.btn_galley;
            this.btnGalley.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnGalley.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(199)))), ((int)(((byte)(162)))), ((int)(((byte)(117)))));
            this.btnGalley.FlatAppearance.BorderSize = 0;
            this.btnGalley.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.btnGalley.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.btnGalley.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGalley.ForeColor = System.Drawing.SystemColors.MenuText;
            this.btnGalley.Location = new System.Drawing.Point(348, 260);
            this.btnGalley.Margin = new System.Windows.Forms.Padding(4);
            this.btnGalley.Name = "btnGalley";
            this.btnGalley.Size = new System.Drawing.Size(106, 40);
            this.btnGalley.TabIndex = 4;
            this.btnGalley.UseVisualStyleBackColor = false;
            this.btnGalley.MouseDown += new System.Windows.Forms.MouseEventHandler(this.ButtonGalleyMouseDown);
            this.btnGalley.MouseEnter += new System.EventHandler(this.ButtonGalleyMouseEnter);
            this.btnGalley.MouseLeave += new System.EventHandler(this.ButtonGalleyMouseLeave);
            // 
            // lblBattleship
            // 
            this.lblBattleship.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.lblBattleship.AutoSize = true;
            this.lblBattleship.BackColor = System.Drawing.Color.Transparent;
            this.lblBattleship.Font = new System.Drawing.Font("Segoe Print", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBattleship.ForeColor = System.Drawing.Color.AliceBlue;
            this.lblBattleship.Location = new System.Drawing.Point(348, 172);
            this.lblBattleship.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBattleship.Name = "lblBattleship";
            this.lblBattleship.Size = new System.Drawing.Size(106, 30);
            this.lblBattleship.TabIndex = 9;
            this.lblBattleship.Text = "Number: 1";
            this.lblBattleship.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // lblCruiser
            // 
            this.lblCruiser.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.lblCruiser.AutoSize = true;
            this.lblCruiser.BackColor = System.Drawing.Color.Transparent;
            this.lblCruiser.Font = new System.Drawing.Font("Segoe Print", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCruiser.ForeColor = System.Drawing.Color.AliceBlue;
            this.lblCruiser.Location = new System.Drawing.Point(348, 300);
            this.lblCruiser.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCruiser.Name = "lblCruiser";
            this.lblCruiser.Size = new System.Drawing.Size(106, 30);
            this.lblCruiser.TabIndex = 10;
            this.lblCruiser.Text = "Number: 3";
            this.lblCruiser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // lblBoat
            // 
            this.lblBoat.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.lblBoat.AutoSize = true;
            this.lblBoat.BackColor = System.Drawing.Color.Transparent;
            this.lblBoat.Font = new System.Drawing.Font("Segoe Print", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBoat.ForeColor = System.Drawing.Color.AliceBlue;
            this.lblBoat.Location = new System.Drawing.Point(348, 364);
            this.lblBoat.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBoat.Name = "lblBoat";
            this.lblBoat.Size = new System.Drawing.Size(106, 30);
            this.lblBoat.TabIndex = 11;
            this.lblBoat.Text = "Number: 3";
            this.lblBoat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // menuStripMain
            // 
            this.menuStripMain.BackColor = System.Drawing.Color.Transparent;
            this.menuStripMain.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.menuStripMain.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.menuStripMain.GripMargin = new System.Windows.Forms.Padding(0);
            this.menuStripMain.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.fileToolStripMenuItem,
                                    this.networkToolStripMenuItem,
                                    this.helpToolStripMenuItem});
            this.menuStripMain.Location = new System.Drawing.Point(0, 0);
            this.menuStripMain.Name = "menuStripMain";
            this.menuStripMain.Padding = new System.Windows.Forms.Padding(0);
            this.menuStripMain.Size = new System.Drawing.Size(800, 24);
            this.menuStripMain.TabIndex = 12;
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(45, 24);
            this.fileToolStripMenuItem.Text = "&File";
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.BackColor = System.Drawing.Color.Transparent;
            this.exitToolStripMenuItem.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.exitToolStripMenuItem.ForeColor = System.Drawing.Color.Black;
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(104, 24);
            this.exitToolStripMenuItem.Text = "&Exit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItemClick);
            // 
            // networkToolStripMenuItem
            // 
            this.networkToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.hostToolStripMenuItem,
                                    this.joinToolStripMenuItem});
            this.networkToolStripMenuItem.Name = "networkToolStripMenuItem";
            this.networkToolStripMenuItem.Size = new System.Drawing.Size(82, 24);
            this.networkToolStripMenuItem.Text = "&Network";
            this.networkToolStripMenuItem.Click += new System.EventHandler(this.NetworkToolStripMenuItemClick);
            // 
            // hostToolStripMenuItem
            // 
            this.hostToolStripMenuItem.Name = "hostToolStripMenuItem";
            this.hostToolStripMenuItem.Size = new System.Drawing.Size(152, 24);
            this.hostToolStripMenuItem.Text = "&Host";
            this.hostToolStripMenuItem.Click += new System.EventHandler(this.HostToolStripMenuItemClick);
            // 
            // joinToolStripMenuItem
            // 
            this.joinToolStripMenuItem.Name = "joinToolStripMenuItem";
            this.joinToolStripMenuItem.Size = new System.Drawing.Size(152, 24);
            this.joinToolStripMenuItem.Text = "&Join";
            this.joinToolStripMenuItem.Click += new System.EventHandler(this.JoinToolStripMenuItemClick);
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.aboutToolStripMenuItem});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(53, 24);
            this.helpToolStripMenuItem.Text = "&Help";
            // 
            // aboutToolStripMenuItem
            // 
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(122, 24);
            this.aboutToolStripMenuItem.Text = "&About";
            this.aboutToolStripMenuItem.Click += new System.EventHandler(this.AboutToolStripMenuItemClick);
            // 
            // playerLabel
            // 
            this.playerLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.playerLabel.AutoSize = true;
            this.playerLabel.BackColor = System.Drawing.Color.Transparent;
            this.playerLabel.Font = new System.Drawing.Font("Segoe Print", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.playerLabel.Location = new System.Drawing.Point(220, 108);
            this.playerLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.playerLabel.Name = "playerLabel";
            this.playerLabel.Size = new System.Drawing.Size(120, 54);
            this.playerLabel.TabIndex = 13;
            this.playerLabel.Text = "Player";
            // 
            // enemyLabel
            // 
            this.enemyLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
                                    | System.Windows.Forms.AnchorStyles.Right)));
            this.enemyLabel.AutoSize = true;
            this.enemyLabel.BackColor = System.Drawing.Color.Transparent;
            this.enemyLabel.Font = new System.Drawing.Font("Segoe Print", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.enemyLabel.Location = new System.Drawing.Point(454, 108);
            this.enemyLabel.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.enemyLabel.Name = "enemyLabel";
            this.enemyLabel.Size = new System.Drawing.Size(127, 54);
            this.enemyLabel.TabIndex = 14;
            this.enemyLabel.Text = "Enemy";
            // 
            // BattleshipsForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Inherit;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.BackColor = System.Drawing.Color.White;
            this.BackgroundImage = global::Battleships.Properties.Resources.Battleships_v10;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(800, 632);
            this.Controls.Add(this.enemyLabel);
            this.Controls.Add(this.playerLabel);
            this.Controls.Add(this.lblBoat);
            this.Controls.Add(this.lblCruiser);
            this.Controls.Add(this.lblBattleship);
            this.Controls.Add(this.lblGalley);
            this.Controls.Add(this.btnBoat);
            this.Controls.Add(this.btnBattleship);
            this.Controls.Add(this.btnCruiser);
            this.Controls.Add(this.btnGalley);
            this.Controls.Add(this.menuStripMain);
            this.DoubleBuffered = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MaximizeBox = false;
            this.Name = "BattleshipsForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Battleships - The Game";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.BattleshipsForm_FormClosing);
            this.Load += new System.EventHandler(this.BattleshipsForm_Load);
            this.menuStripMain.ResumeLayout(false);
            this.menuStripMain.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem joinToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem hostToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem networkToolStripMenuItem;

        private System.Windows.Forms.Label enemyLabel;
        private System.Windows.Forms.Label playerLabel;

        #endregion

        private System.Windows.Forms.Button btnGalley;
        private System.Windows.Forms.Button btnCruiser;
        private System.Windows.Forms.Button btnBattleship;
        private System.Windows.Forms.Button btnBoat;
        private System.Windows.Forms.Label lblGalley;
        private System.Windows.Forms.Label lblBattleship;
        private System.Windows.Forms.Label lblCruiser;
        private System.Windows.Forms.Label lblBoat;
        private System.Windows.Forms.ToolTip toolTipMouse;
        private System.Windows.Forms.MenuStrip menuStripMain;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;

        // unused?
        // private DoubleBuffered.Panel_DoubleBuffered panel_Status;
    }
}