// <auto-generated />
namespace Battleships
{
    public partial class ClientGameForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">True if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.lblIP = new System.Windows.Forms.Label();
            this.textboxIP = new System.Windows.Forms.TextBox();
            this.textboxPort = new System.Windows.Forms.TextBox();
            this.lblPort = new System.Windows.Forms.Label();
            this.btnConnect = new System.Windows.Forms.Button();
            this.label3 = new System.Windows.Forms.Label();
            this.btnDisconnect = new System.Windows.Forms.Button();
            this.listboxRx = new System.Windows.Forms.ListBox();
            this.buttonReady = new System.Windows.Forms.Button();
            this.toolTipButtons = new System.Windows.Forms.ToolTip(this.components);
            this.SuspendLayout();
            // 
            // lblIP
            // 
            this.lblIP.AutoSize = true;
            this.lblIP.Location = new System.Drawing.Point(17, 25);
            this.lblIP.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblIP.Name = "lblIP";
            this.lblIP.Size = new System.Drawing.Size(70, 17);
            this.lblIP.TabIndex = 0;
            this.lblIP.Text = "Server IP:";
            // 
            // textboxIP
            // 
            this.textboxIP.Location = new System.Drawing.Point(97, 16);
            this.textboxIP.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textboxIP.Name = "textboxIP";
            this.textboxIP.Size = new System.Drawing.Size(164, 22);
            this.textboxIP.TabIndex = 1;
            // 
            // textboxPort
            // 
            this.textboxPort.Location = new System.Drawing.Point(97, 48);
            this.textboxPort.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textboxPort.Name = "textboxPort";
            this.textboxPort.Size = new System.Drawing.Size(80, 22);
            this.textboxPort.TabIndex = 3;
            this.textboxPort.Text = "8000";
            // 
            // lblPort
            // 
            this.lblPort.AutoSize = true;
            this.lblPort.Location = new System.Drawing.Point(17, 57);
            this.lblPort.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblPort.Name = "lblPort";
            this.lblPort.Size = new System.Drawing.Size(38, 17);
            this.lblPort.TabIndex = 2;
            this.lblPort.Text = "Port:";
            // 
            // btnConnect
            // 
            this.btnConnect.BackColor = System.Drawing.Color.Blue;
            this.btnConnect.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
            this.btnConnect.ForeColor = System.Drawing.Color.Yellow;
            this.btnConnect.Location = new System.Drawing.Point(299, 16);
            this.btnConnect.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnConnect.Name = "btnConnect";
            this.btnConnect.Size = new System.Drawing.Size(120, 57);
            this.btnConnect.TabIndex = 4;
            this.btnConnect.Text = "Connect";
            this.toolTipButtons.SetToolTip(this.btnConnect, "Verbinde dich mit einem Spiel (Über das Internet oder LAN)");
            this.btnConnect.UseVisualStyleBackColor = false;
            this.btnConnect.Click += new System.EventHandler(this.ButtonConnect_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(21, 91);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(147, 17);
            this.label3.TabIndex = 5;
            this.label3.Text = "Message from Server:";
            // 
            // btnDisconnect
            // 
            this.btnDisconnect.BackColor = System.Drawing.Color.Red;
            this.btnDisconnect.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
            this.btnDisconnect.ForeColor = System.Drawing.Color.Yellow;
            this.btnDisconnect.Location = new System.Drawing.Point(299, 80);
            this.btnDisconnect.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnDisconnect.Name = "btnDisconnect";
            this.btnDisconnect.Size = new System.Drawing.Size(120, 57);
            this.btnDisconnect.TabIndex = 7;
            this.btnDisconnect.Text = "Disconnect";
            this.btnDisconnect.UseVisualStyleBackColor = false;
            this.btnDisconnect.Click += new System.EventHandler(this.ButtonDisconnect_Click);
            // 
            // listboxRx
            // 
            this.listboxRx.FormattingEnabled = true;
            this.listboxRx.HorizontalScrollbar = true;
            this.listboxRx.ItemHeight = 16;
            this.listboxRx.Location = new System.Drawing.Point(21, 111);
            this.listboxRx.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.listboxRx.Name = "listboxRx";
            this.listboxRx.Size = new System.Drawing.Size(268, 148);
            this.listboxRx.TabIndex = 8;
            // 
            // buttonReady
            // 
            this.buttonReady.BackColor = System.Drawing.Color.Blue;
            this.buttonReady.Enabled = false;
            this.buttonReady.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
            this.buttonReady.ForeColor = System.Drawing.Color.Yellow;
            this.buttonReady.Location = new System.Drawing.Point(299, 144);
            this.buttonReady.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.buttonReady.Name = "buttonReady";
            this.buttonReady.Size = new System.Drawing.Size(120, 57);
            this.buttonReady.TabIndex = 9;
            this.buttonReady.Text = "Ready";
            this.toolTipButtons.SetToolTip(this.buttonReady, "Gib an, dass du Bereit zum Spielen bist");
            this.buttonReady.UseVisualStyleBackColor = false;
            this.buttonReady.Click += new System.EventHandler(this.ButtonReady_Click);
            // 
            // toolTipButtons
            // 
            this.toolTipButtons.IsBalloon = true;
            // 
            // ClientGameForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(431, 268);
            this.Controls.Add(this.buttonReady);
            this.Controls.Add(this.listboxRx);
            this.Controls.Add(this.btnDisconnect);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.btnConnect);
            this.Controls.Add(this.textboxPort);
            this.Controls.Add(this.lblPort);
            this.Controls.Add(this.textboxIP);
            this.Controls.Add(this.lblIP);
            this.DoubleBuffered = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = global::Battleships.Properties.Resources.battleships_icon;
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.MaximizeBox = false;
            this.Name = "ClientGameForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Connect to Game";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.ClientGameFormClosed);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Label lblIP;
        private System.Windows.Forms.TextBox textboxIP;
        private System.Windows.Forms.TextBox textboxPort;
        private System.Windows.Forms.Label lblPort;
        private System.Windows.Forms.Button btnConnect;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button btnDisconnect;
        private System.Windows.Forms.ListBox listboxRx;
        private System.Windows.Forms.Button buttonReady;
        private System.Windows.Forms.ToolTip toolTipButtons;
    }
}