// <auto-generated />
namespace Battleships
{
    public partial class HostGameForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">True if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.textBoxIP = new System.Windows.Forms.TextBox();
            this.lblIP = new System.Windows.Forms.Label();
            this.lblPort = new System.Windows.Forms.Label();
            this.textBoxPort = new System.Windows.Forms.TextBox();
            this.btnCloseGame = new System.Windows.Forms.Button();
            this.btnHostGame = new System.Windows.Forms.Button();
            this.labelStatusMessage = new System.Windows.Forms.Label();
            this.listboxMessage = new System.Windows.Forms.ListBox();
            this.btnRdy = new System.Windows.Forms.Button();
            this.btnExtIp = new System.Windows.Forms.Button();
            this.toolTipButtons = new System.Windows.Forms.ToolTip(this.components);
            this.btnInternIP = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // textBoxIP
            // 
            this.textBoxIP.Location = new System.Drawing.Point(113, 15);
            this.textBoxIP.Margin = new System.Windows.Forms.Padding(4);
            this.textBoxIP.Name = "textBoxIP";
            this.textBoxIP.ReadOnly = true;
            this.textBoxIP.Size = new System.Drawing.Size(159, 22);
            this.textBoxIP.TabIndex = 16;
            // 
            // lblIP
            // 
            this.lblIP.Location = new System.Drawing.Point(17, 15);
            this.lblIP.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblIP.Name = "lblIP";
            this.lblIP.Size = new System.Drawing.Size(75, 20);
            this.lblIP.TabIndex = 15;
            this.lblIP.Text = "Server IP";
            // 
            // lblPort
            // 
            this.lblPort.Location = new System.Drawing.Point(17, 44);
            this.lblPort.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblPort.Name = "lblPort";
            this.lblPort.Size = new System.Drawing.Size(64, 20);
            this.lblPort.TabIndex = 14;
            this.lblPort.Text = "Port";
            // 
            // textBoxPort
            // 
            this.textBoxPort.Location = new System.Drawing.Point(113, 44);
            this.textBoxPort.Margin = new System.Windows.Forms.Padding(4);
            this.textBoxPort.Name = "textBoxPort";
            this.textBoxPort.Size = new System.Drawing.Size(52, 22);
            this.textBoxPort.TabIndex = 13;
            this.textBoxPort.Text = "8000";
            // 
            // btnCloseGame
            // 
            this.btnCloseGame.BackColor = System.Drawing.Color.Red;
            this.btnCloseGame.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCloseGame.ForeColor = System.Drawing.Color.Yellow;
            this.btnCloseGame.Location = new System.Drawing.Point(411, 71);
            this.btnCloseGame.Margin = new System.Windows.Forms.Padding(4);
            this.btnCloseGame.Name = "btnCloseGame";
            this.btnCloseGame.Size = new System.Drawing.Size(117, 49);
            this.btnCloseGame.TabIndex = 18;
            this.btnCloseGame.Text = "Stop Server";
            this.btnCloseGame.UseVisualStyleBackColor = false;
            this.btnCloseGame.Click += new System.EventHandler(this.ButtonCloseGame_Click);
            // 
            // btnHostGame
            // 
            this.btnHostGame.BackColor = System.Drawing.Color.Blue;
            this.btnHostGame.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHostGame.ForeColor = System.Drawing.Color.Yellow;
            this.btnHostGame.Location = new System.Drawing.Point(411, 15);
            this.btnHostGame.Margin = new System.Windows.Forms.Padding(4);
            this.btnHostGame.Name = "btnHostGame";
            this.btnHostGame.Size = new System.Drawing.Size(117, 49);
            this.btnHostGame.TabIndex = 17;
            this.btnHostGame.Text = "Start Server";
            this.toolTipButtons.SetToolTip(this.btnHostGame, "Start a game which others can join.");
            this.btnHostGame.UseVisualStyleBackColor = false;
            this.btnHostGame.Click += new System.EventHandler(this.ButtonHostGame_Click);
            // 
            // labelStatusMessage
            // 
            this.labelStatusMessage.Location = new System.Drawing.Point(17, 110);
            this.labelStatusMessage.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelStatusMessage.Name = "labelStatusMessage";
            this.labelStatusMessage.Size = new System.Drawing.Size(149, 20);
            this.labelStatusMessage.TabIndex = 20;
            this.labelStatusMessage.Text = "Status Message:";
            // 
            // listboxMessage
            // 
            this.listboxMessage.FormattingEnabled = true;
            this.listboxMessage.HorizontalScrollbar = true;
            this.listboxMessage.ItemHeight = 16;
            this.listboxMessage.Location = new System.Drawing.Point(21, 133);
            this.listboxMessage.Margin = new System.Windows.Forms.Padding(4);
            this.listboxMessage.Name = "listboxMessage";
            this.listboxMessage.Size = new System.Drawing.Size(376, 148);
            this.listboxMessage.TabIndex = 21;
            // 
            // btnRdy
            // 
            this.btnRdy.BackColor = System.Drawing.Color.Blue;
            this.btnRdy.Enabled = false;
            this.btnRdy.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRdy.ForeColor = System.Drawing.Color.Yellow;
            this.btnRdy.Location = new System.Drawing.Point(411, 133);
            this.btnRdy.Margin = new System.Windows.Forms.Padding(4);
            this.btnRdy.Name = "btnRdy";
            this.btnRdy.Size = new System.Drawing.Size(117, 49);
            this.btnRdy.TabIndex = 22;
            this.btnRdy.Text = "Ready";
            this.toolTipButtons.SetToolTip(this.btnRdy, "Gib an, dass du bereit zum Spielen bist");
            this.btnRdy.UseVisualStyleBackColor = false;
            this.btnRdy.Click += new System.EventHandler(this.ButtonReady_Click);
            // 
            // btnExtIp
            // 
            this.btnExtIp.Location = new System.Drawing.Point(299, 15);
            this.btnExtIp.Margin = new System.Windows.Forms.Padding(4);
            this.btnExtIp.Name = "btnExtIp";
            this.btnExtIp.Size = new System.Drawing.Size(100, 49);
            this.btnExtIp.TabIndex = 23;
            this.btnExtIp.Text = "Find External IP";
            this.toolTipButtons.SetToolTip(this.btnExtIp, "Determine your external IP address  for internet play.");
            this.btnExtIp.UseVisualStyleBackColor = true;
            this.btnExtIp.Click += new System.EventHandler(this.ButtonExternalIp_Click);
            // 
            // toolTipButtons
            // 
            this.toolTipButtons.IsBalloon = true;
            // 
            // btnInternIP
            // 
            this.btnInternIP.Location = new System.Drawing.Point(299, 71);
            this.btnInternIP.Margin = new System.Windows.Forms.Padding(4);
            this.btnInternIP.Name = "btnInternIP";
            this.btnInternIP.Size = new System.Drawing.Size(100, 49);
            this.btnInternIP.TabIndex = 24;
            this.btnInternIP.Text = "Find Internal IP";
            this.toolTipButtons.SetToolTip(this.btnInternIP, "Determine your internal IP address for LAN play.");
            this.btnInternIP.UseVisualStyleBackColor = true;
            this.btnInternIP.Click += new System.EventHandler(this.ButtonInternalIP_Click);
            // 
            // HostGameForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(544, 292);
            this.Controls.Add(this.btnInternIP);
            this.Controls.Add(this.btnExtIp);
            this.Controls.Add(this.btnRdy);
            this.Controls.Add(this.listboxMessage);
            this.Controls.Add(this.labelStatusMessage);
            this.Controls.Add(this.btnCloseGame);
            this.Controls.Add(this.btnHostGame);
            this.Controls.Add(this.textBoxIP);
            this.Controls.Add(this.lblIP);
            this.Controls.Add(this.lblPort);
            this.Controls.Add(this.textBoxPort);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = global::Battleships.Properties.Resources.battleships_icon;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MaximizeBox = false;
            this.Name = "HostGameForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Host Game";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.HostGameForm_FormClosed);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TextBox textBoxIP;
        private System.Windows.Forms.Label lblIP;
        private System.Windows.Forms.Label lblPort;
        private System.Windows.Forms.TextBox textBoxPort;
        private System.Windows.Forms.Button btnCloseGame;
        private System.Windows.Forms.Button btnHostGame;
        private System.Windows.Forms.Label labelStatusMessage;
        private System.Windows.Forms.ListBox listboxMessage;
        private System.Windows.Forms.Button btnRdy;
        private System.Windows.Forms.Button btnExtIp;
        private System.Windows.Forms.ToolTip toolTipButtons;
        private System.Windows.Forms.Button btnInternIP;
    }
}